title:   Sanchita Biswas
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Organized individual with strong analytical skills and exceptional attention to details, identify opportunities to create efficiency
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="https://www.linkedin.com/in/sanchita-biswas/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/sanchita.biswas">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/sanchitabiswas/About-Me-Sanchita-Biswas-bae89db5a6ef4afaa17fce9e9e341f7e">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
